### ISSUE TITLE
Feature # 1: User can create a run entry

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/runners-high#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a run entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create a run entry which will be added to their list of logged runs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
 ![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/e6ab0c5c-b638-4cb5-8ac1-3f077e146400)
Mobile:
 ![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/5bd4ad4f-bfbe-4efa-ba27-17247b218f2b)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.ts` to ...
      - [ ] Handle POST requests to add a new run entry to the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Install react-router-dom dependencies and add the BrowserRouter Component to main.tsx
- [x] Create routes to contain all of the project's components
- [x] Create a header component including the Outlet component
- [x] Create a component to serve as a form to create a new run entry
- [x] Add components as routes
- [x] Create a fetch request to POST new run entry

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
