### ISSUE TITLE
Feature #2: User can view run entries

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/runners-high#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their run entries

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see each of their run entries with all of its associated data.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/9e9b0f93-b062-46ee-b217-6f59ad90b276)
Mobile:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/3b8e220e-b37b-4414-a98d-dba8434325f9)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.ts` to ...
- [x] Submit a GET request for all run entries
- [x] Test functionality with HTTPie 

### ⚡ Client Tasks

- [x] Create a component to display all run entries available in the database
- [x]  Add a useEffect to display all run entries once upon page render
- [x] Call the fetch request for all run entries in this useEffect
- [x] Add functionality to display a loading page if the page is loading
- [x] Add functionality to display an error message if there was an error when loading the page

- [x] In `locations.ts`
- [x] Add a fetch request to GET all run entries available in the database with the appropriate userId

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
