### ISSUE TITLE
Feature #3: User can edit a run entry

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/runners-high#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a run entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can edit one of their run entries that is in the list of their logged runs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/f364d795-1712-4756-bd3a-44207ccc13dc)
Mobile:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/a6bee6bb-939f-403b-b253-41fdced05a23)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create a PUT request to update the chosen run entry, include a where clause for the runId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Add functionality to the Edit Run button to navigate to the Run form

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
