### ISSUE TITLE
Feature #4: User can delete a run entry

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/runners-high#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a run entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can delete a run entry that is part of their list of run entries.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/df785751-7ffa-4f6d-81bc-7b0da1bafc58)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.ts` to send a DELETE request, include a where clause with the runId, sendStatus back to the client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add functionality to the delete button that triggers a modal to open upon click
- [x] Create a useRef hook to achieve this functionality
- [x] Add functionality to close the modal upon click
- [x] Add functionality to the confirm button to send the DELETE request upon click
- [x] Add functionality to the confirm button to send a GET request requesting all run entries to reload the updated run entries

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
