### ISSUE TITLE
Feature #5: User can create an account

### ISSUE THREAD

**Issue by Malcolm-Abbott** [Malcolm-Abbott/runners-high#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create an account to store their personalized run information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop Login:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/e43000a5-1b20-41d2-bcd2-d660a3d0b52b)
Mobile Login:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/8381a678-cd62-4064-adef-aed30da2cc9b)
Universal Sign-Up:
![image](https://github.com/Malcolm-Abbott/runners-high/assets/136769102/a12828d1-4487-4307-b20b-b45b2c0c44ec)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create a guest user account

### ☁️ Server Tasks

- [x] In `server.ts`
- [x] Create a hashKey
- [x] Import argon2 and jwt
- [x] Create an Auth type and User type
- [x] Create POST requests for sign-up and sign-in functionality
- [x] Update HTTP requests to run the authorization middleware between the URL and the asynchronous callback function
- [x] Update HTTP requests to include the req.user?.userId in the params
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the login page
- [x] Create a component for the sign up page
- [x] In `SignUp.tsx`
- [x] Create a handleSubmit function to obtain the form data, send the data via a fetch POST request, and navigate to the index route

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
